version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cities-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cities
    ports:
      - "5433:5432"  # redireciona porta externa 5433 pra interna 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
